using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BilavNSE_WeightageUtility
{
    public class GetQuery
    {
        public static string UT_NSEWTBOD_INSERT_CMD
        {
            get
            {
                return @"INSERT INTO UT_NSEWTBOD (INDEX_NAME,VALUE_DATE,MKT,SERIES_NAME,SYMBOL_NAME,ISIN,SECURITY_NAME,BASIC_INDUSTRY,PREV_CL_PR,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,NET_TRDVAL,NET_TRDATY,IND_SEC,CORP_IND,TRADES,HI_52_WK,LO_52_WK,ISSUE_CAP,INVESTIBLE_FACTTOR,CAP_FACTOR,ADJ_CLOSE_PRICE,INDEX_MKT_CAP,WEIGHTAGE ,INDEXED_UNITS,INP_DT_TM)" + //INP_DT_TM
                                            "VALUES(:PINDEX_NAME,:PVALUE_DATE,:PMKT,:PSERIES_NAME,:PSYMBOL_NAME,:PISIN,:PSECURITY_NAME,:PBASIC_INDUSTRY,:PPREV_CL_PR,:POPEN_PRICE,:PHIGH_PRICE,:PLOW_PRICE,:PCLOSE_PRICE,:PNET_TRDVAL,:PNET_TRDATY,:PIND_SEC,:PCORP_IND,:PTRADES,:PHI_52_WK,:PLO_52_WK,:PISSUE_CAP,:PINVESTIBLE_FACTTOR,:PCAP_FACTOR,:PADJ_CLOSE_PRICE,:PINDEX_MKT_CAP,:WEIGHTAGE ,:PINDEXED_UNITS,:PINP_DT_TM)";
            }
        }

        public static string UT_NSEWTEOD_INSERT_CMD
        {
            get
            {
                return @"INSERT INTO UT_NSEWTEOD (INDEX_NAME,VALUE_DATE,MKT,SERIES_NAME,SYMBOL_NAME,ISIN,SECURITY_NAME,BASIC_INDUSTRY,PREV_CL_PR,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,NET_TRDVAL,NET_TRDATY,IND_SEC,CORP_IND,TRADES,HI_52_WK,LO_52_WK,ISSUE_CAP,INVESTIBLE_FACTTOR,CAP_FACTOR,ADJ_CLOSE_PRICE,INDEX_MKT_CAP, WEIGHTAGE ,INDEXED_UNITS,INP_DT_TM)" +//INP_DT_TM
                                           "VALUES(:PINDEX_NAME,:PVALUE_DATE,:PMKT,:PSERIES_NAME,:PSYMBOL_NAME,:PISIN,:PSECURITY_NAME,:PBASIC_INDUSTRY,:PPREV_CL_PR,:POPEN_PRICE,:PHIGH_PRICE,:PLOW_PRICE,:PCLOSE_PRICE,:PNET_TRDVAL,:PNET_TRDATY,:PIND_SEC,:PCORP_IND,:PTRADES,:PHI_52_WK,:PLO_52_WK,:PISSUE_CAP,:PINVESTIBLE_FACTTOR,:PCAP_FACTOR,:PADJ_CLOSE_PRICE,:PINDEX_MKT_CAP,:WEIGHTAGE ,:PINDEXED_UNITS,:PINP_DT_TM)";
            }
        }

        public static string SELECT_QUERY_UT_NSEWTBOD = "SELECT * FROM UT_NSEWTBOD where INDEX_NAME = PINDEX_NAME and VALUE_DATE = DATE and ISIN =PISIN";

        public static string SELECT_QUERY_UT_NSEWTEOD = "SELECT * FROM  UT_NSEWTBOD where INDEX_NAME=PINDEX_NAME and VALUE_DATE=DATE and ISIN =PISIN";

    }
}

    
 
